### ISSUE TITLE
Remove GDI+ bitmap storage

### ISSUE THREAD

**Issue by felixjones** [avarisc/OpenGame.exe#27]
This is something that should eventually be done when dependency on these is reduced to simply the texture upload stage.

At the moment, the same images are stored in both GPU and system memory, which is wasteful. The GDI+ bitmaps can be migrated to OpenGL textures once all the dependencies are removed.

Any software bitmap manipulation should download the GPU memory into a temporary buffer that mimics the RGSS bitmaps structure.

**Comment by aphadeon** [comment]
I would reference you to #17 , as this was part of the intention of that task.
